def main():
    location = input("Привет! Выбери локацию (school | hospital | park): ")
    if location == "school":
        ...
    elif location == "hospital":
        ...
    elif location == "park":
        ...